[2021-11-02 12:32:14,457: INFO: stage_01_prepare]: 
********************
[2021-11-02 12:32:14,457: INFO: stage_01_prepare]: >>>>> stage One started <<<<<
[2021-11-02 12:32:14,458: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-02 12:32:14,459: INFO: common]: yaml file: params.yaml loaded successfully
[2021-11-02 12:32:14,459: INFO: stage_01_prepare]: >>>>> stage One completed! <<<<<

[2021-11-02 17:32:22,642: INFO: stage_01_prepare]: 
********************
[2021-11-02 17:32:22,642: INFO: stage_01_prepare]: >>>>> stage One started <<<<<
[2021-11-02 17:32:22,643: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-02 17:32:22,647: ERROR: stage_01_prepare]: mapping values are not allowed here
  in "params.yaml", line 5, column 7
Traceback (most recent call last):
  File "src/stage_01_prepare.py", line 44, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_prepare.py", line 21, in main
    params = read_yaml(params_path)
  File "c:\users\balay\pycharmprojects\dvc_nlp_simple_usecase\dvc_nlp_simple_usecase\src\utils\common.py", line 10, in read_yaml
    content = yaml.safe_load(yaml_file)
  File "C:\Users\balay\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\balay\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\balay\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\balay\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\balay\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\balay\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\balay\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\balay\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\balay\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\balay\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\balay\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "C:\Users\balay\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "params.yaml", line 5, column 7
[2021-11-02 18:01:47,316: INFO: stage_01_prepare]: 
********************
[2021-11-02 18:01:47,316: INFO: stage_01_prepare]: >>>>> stage One started <<<<<
[2021-11-02 18:01:47,318: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-02 18:01:47,319: INFO: common]: yaml file: params.yaml loaded successfully
[2021-11-02 18:01:47,319: INFO: common]: directory is created at artifacts\prepared
[2021-11-02 18:01:47,319: INFO: stage_01_prepare]: >>>>> stage One completed! <<<<<

[2021-11-02 20:00:52,937: INFO: stage_01_prepare]: 
********************
[2021-11-02 20:00:52,938: INFO: stage_01_prepare]: >>>>> stage One started <<<<<
[2021-11-02 20:00:52,940: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-02 20:00:52,941: INFO: common]: yaml file: params.yaml loaded successfully
[2021-11-02 20:00:52,941: INFO: common]: directory is created at artifacts\prepared
[2021-11-02 20:00:56,118: INFO: stage_01_prepare]: >>>>> stage One completed! <<<<<

[2021-11-02 23:41:08,999: INFO: stage_01_prepare]: 
********************
[2021-11-02 23:41:08,999: INFO: stage_01_prepare]: >>>>> stage One started <<<<<
[2021-11-02 23:41:09,001: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-02 23:41:09,001: INFO: common]: yaml file: params.yaml loaded successfully
[2021-11-02 23:41:09,001: INFO: common]: directory is created at artifacts\prepared
[2021-11-02 23:41:11,325: INFO: stage_01_prepare]: >>>>> stage One completed! <<<<<

